name: Cordova Build (VolleyTouch HTML)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK cmdline-tools
        run: |
          set -eux
          SDK="$GITHUB_WORKSPACE/android-sdk"
          mkdir -p "$SDK/cmdline-tools"
          cd "$SDK/cmdline-tools"
          curl -L -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip
          rm -f tools.zip
          mv cmdline-tools latest
          export PATH="$SDK/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --sdk_root="$SDK" "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
          yes | sdkmanager --sdk_root="$SDK" --licenses || true
          echo "ANDROID_SDK_ROOT=$SDK" >> $GITHUB_ENV
          echo "$SDK/platform-tools" >> $GITHUB_PATH
          echo "$SDK/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Install Cordova
        run: npm i -g cordova@12

      - name: Build Cordova Android APK
        run: |
          set -eux
          # Create Cordova project
          cordova create app com.yourname.volleytouch VolleyTouch
          # Copy your web assets into app/www
          if [ -d "www" ]; then
            rm -rf app/www
            cp -r www app/www
          elif [ -f "index.html" ]; then
            rm -rf app/www
            mkdir -p app/www
            cp index.html app/www/
          else
            echo "::error::No web assets found. Put your game in 'www/' (recommended) or at least an 'index.html' at repo root."
            exit 1
          fi
          # Add Android and build debug APK
          cd app
          cordova platform add android@12
          cordova build android --debug
          ls -la platforms/android/app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: volleytouch-html-apk
          path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
